Repository privateerproj/privateer, pull requests merged in 2025-01, with the labels that each got.

#59 feat: automate pr labeling and releases
  .github/release-drafter.yml
  .github/workflows/auto-labeler.yml
  .github/workflows/goreleaser.yml
  .github/workflows/pr-title.yml
  .github/workflows/release.yml
  go.mod
  go.sum
Labels: feature, release

#61 fix: goreleaser stuff
  .github/workflows/goreleaser.yml
  .goreleaser.yaml
Labels: fix

#64 fix: move goreleaser action workflow job to release workflow to get go binaries attached to release via automation
  .github/workflows/goreleaser.yml
  .github/workflows/release.yml
Labels: fix

#70 chore: add Dockerfile to build release image
  Dockerfile
Labels: maintenance

#71 fix: cobra presistenflags getting wired up at the correct time
  cmd/root.go
  go.mod
  go.sum
Labels: fix, release

#73 docs: update how-to-generate-example-plugin.md with missing parts
  docs/how-to-generate-example-plugin.md
Labels: documentation

#75 chore: update after removal of readconfig func
  cmd/root.go
  go.mod
  go.sum
Labels: maintenance, release

#76 fix: revert the revert
  cmd/root.go
  go.mod
  go.sum
Labels: fix, release

#78 ci: Bugs should increment patch version
  .github/release-drafter.yml
Labels: automation

#80 docs: update how-to-generate-example-plugin.md
  .github/workflows/ci.yml
  .github/workflows/site.yml
  docs/how-to-generate-example-plugin.md
Labels: documentation

#83 chore: auto-labeler workflow perms and goreleaser config
  .github/workflows/auto-labeler.yml
  .goreleaser.yaml
Labels: maintenance

#84 feat: nuanced exit codes
  cmd/run.go
Labels: feature
