Repository privateerproj/privateer, pull requests merged in 2025-03, with the labels that each got.

#96 feat: upgrade to SDK v1.0.2
  cmd/generate-plugin.go
  cmd/list.go
  cmd/run.go
  example-config.yml
  go.mod
  go.sum
Labels: feature

#100 chore: remove go- prefix on make targets
  Dockerfile
  Makefile
Labels: maintenance

#102 test: Add acceptance tests to CI workflow
  .github/workflows/ci.yml
  build/github/acceptance_test.sh
  test/data/CCC.VPC_2025.01.yaml
Labels: automation

#105 feat: linting
  .github/workflows/lint.yml
  cmd/generate-plugin.go
  cmd/install.go
  cmd/list.go
  cmd/version.go
Labels: feature
